## these variables are CI-specific
variables:
  DOCKER_DRIVER: overlay2
  CODE_COVERAGE_MIN: 80

stages:
  - install
  - quality_check
  - test

install:
  only:
    - merge_requests
  stage: install
  variables:
    APP_ENV: test
  cache:
    key: $SYMFONY_REQUIRE-$CI_MERGE_REQUEST_ID
    paths:
      - vendor/
  parallel:
    matrix:
      - SYMFONY_REQUIRE: ['4.4.*', '5.4.*']
  script:
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex
    - composer update --no-interaction --prefer-dist --optimize-autoloader --ansi
    - vendor/bin/simple-phpunit install

quality_check:
  only:
    - merge_requests
  stage: quality_check
  cache:
    key: 4.4.*-$CI_MERGE_REQUEST_ID
    policy: pull
    paths:
      - vendor/
  variables:
    APP_ENV: test
  script:
    - vendor/bin/php-cs-fixer fix --dry-run --diff --using-cache=no --ansi --show-progress=none
    - vendor/bin/psalm --no-cache --no-progress
    - vendor/bin/phpstan analyse --ansi --no-progress

test:
  only:
    - merge_requests
  stage: test
  coverage: '/Code coverage is \d+.\d+%/'
  cache:
    key: $SYMFONY_REQUIRE-$CI_MERGE_REQUEST_ID
    policy: pull
    paths:
      - vendor/
  parallel:
    matrix:
      - SYMFONY_REQUIRE: ['4.4.*', '5.4.*']
  variables:
    APP_ENV: test
  script:
    - bash ./scripts/unit.sh --coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: artifacts/code-coverage-cobertura.xml
    paths:
      - artifacts/code-coverage.tar.gz
    expire_in: 1 day